export const base_url = "http://localhost:1337";
export const images_url = "http://localhost:1337/images";
export const nav_url = "http://localhost:1337/main-menu";
export const en_nav_url = "http://localhost:1337/en-main-menu"
export const en_summary_url = "http://localhost:1337/en-summaries";
export const tr_summary_url = "http://localhost:1337/tr-summaries";
export const en_adresses_url = "http://localhost:1337/en-adresses";
export const tr_adresses_url = "http://localhost:1337/tr-adresses";
export const social_media_url = "http://localhost:1337/social-medias";
export const tr_about_url = "http://localhost:1337/tr-abouts";
export const en_about_url = "http://localhost:1337/en-abouts";
export const offices_url="http://localhost:1337/offices";
export const en_offices_url="http://localhost:1337/en-offices";